language: scala

scala:
   - 2.11.7
   - 2.12.0

script:
   - sbt ++$TRAVIS_SCALA_VERSION test

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

jdk:
  - oraclejdk8